-- hl.config({ autogenerated = true )} -- remove this line to remove the warning

require("modules.autostart")
require("modules.binds")
require("modules.decoration")
require("modules.EV")
require("modules.input")
require("modules.monitors")
require("modules.optimization")
require("modules.permissions")
require("modules.window-rule")

-- For Noctalia Color templates
require("noctalia").apply_theme()
