-- hl.config({ autogenerated = true )} -- remove this line to remove the warning

require("modules.autostart")
require("modules.binds")
require("modules.decoration")
require("modules.ev")
require("modules.input")
require("modules.misc")
require("modules.monitors")
require("modules.permissions")
require("modules.windows")
require("modules.optimization")


-- For Noctalia Color templates
require("noctalia").apply_theme()
