-- hl.config({ autogenerated = true )} -- remove this line to remove the warning

require("modules.autostart")
require("modules.binds")
require("modules.decoration")
require("modules.input")
require("modules.monitors")
require("modules.optimization")

