[colors.primary]
background = '#131314'
foreground = '#e4e2e3'

[colors.cursor]
text = '#131314'
cursor = '#e4e2e3'

[colors.vi_mode_cursor]
text = '#131314'
cursor = '#b6c9d8'

[colors.search.matches]
foreground = '#43474b'
background = '#d4c0d7'

[colors.search.focused_match]
foreground = '#43474b'
background = '#b6c9d8'

[colors.footer_bar]
foreground = '#43474b'
background = '#e4e2e3'

[colors.hints.start]
foreground = '#43474b'
background = '#c1c7ce'

[colors.hints.end]
foreground = '#43474b'
background = '#c1c7ce'

[colors.selection]
text = '#c3c7cb'
background = '#43474b'


[colors.normal]
black   = '#43474b'
red     = '#ffb4ab'
green   = '#b6c9d8'
yellow  = '#c1c7ce'
blue    = '#d4c0d7'
magenta = '#b6c9d8'
cyan    = '#c1c7ce'
white   = '#e4e2e3'


[colors.bright]
black   = '#8d9195'
red     = '#ffb4ab'
green   = '#b6c9d8'
yellow  = '#c1c7ce'
blue    = '#d4c0d7'
magenta = '#b6c9d8'
cyan    = '#c1c7ce'
white   = '#e4e2e3'


[colors.dim]
black   = '#43474b'
red     = '#ffb4ab'
green   = '#b6c9d8'
yellow  = '#c1c7ce'
blue    = '#d4c0d7'
magenta = '#b6c9d8'
cyan    = '#c1c7ce'
white   = '#e4e2e3'
