
[font]
size = 12.0

[font.normal]
family = "BigBlueTermPlus Nerd Font"
style = "Bold"

[cursor]
style = "Block"
smooth_motion = true
smooth_motion_factor = 0.5
smooth_motion_spring = 0.5

[general]
import = ["~/.config/alacritty/themes/noctalia.toml"]
